// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package model

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg *CreateOrganizationParams) (*Organization, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
