// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Organization struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"`
}

type SignupInput struct {
	OrgName  string `json:"orgName"`
	UserName string `json:"userName"`
}

type SignupPayload struct {
	Ok bool `json:"ok"`
}

type User struct {
	ID             string        `json:"id"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
	OrganizationID string        `json:"organizationId"`
	Name           string        `json:"name"`
	Organization   *Organization `json:"organization"`
}
